# Configuration pour les releases automatiques GitHub

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - question
      - invalid
      - wontfix
    authors:
      - dependabot
      - github-actions[bot]
  categories:
    - title: 🚀 Nouvelles Fonctionnalités
      labels:
        - enhancement
        - feature
        - new-feature
    - title: 🐛 Corrections de Bugs
      labels:
        - bug
        - bugfix
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
        - cleanup
    - title: ⚡ Performances
      labels:
        - performance
        - optimization
    - title: 🔒 Sécurité
      labels:
        - security
        - vulnerability
    - title: 🎨 Interface Utilisateur
      labels:
        - ui
        - ux
        - design
    - title: 🏗️ Build et CI/CD
      labels:
        - build
        - ci
        - cd
        - workflow
    - title: 📦 Dépendances
      labels:
        - dependencies
        - deps
    - title: 🧪 Tests
      labels:
        - test
        - testing
    - title: 🌐 Internationalisation
      labels:
        - i18n
        - l10n
        - translation
    - title: ♿ Accessibilité
      labels:
        - accessibility
        - a11y
    - title: 📱 Compatibilité
      labels:
        - compatibility
        - platform
    - title: 🔄 Autres Changements
      labels:
        - "*"